#!/usr/bin/env bash

get_username() {
    gopass show "$1" |
	awk '/^username/ {print $2}' |
	tr -d '\n' |
	xclip -selection clipboard
}

get_password() {
    gopass -c "$1"
}

if [[ $ROFI_RETV -eq 0 ]]; then
    for entry in $(gopass list -f); do
        echo "$entry"
    done
elif [[ $ROFI_RETV -eq 1 ]]; then
    if [[ -z "${ROFI_INFO:-}" ]]; then
        echo -en "username\0info\x1f$1\n"
        echo -en "password\0info\x1f$1\n"
    else
        if [[ $1 == "username" ]]; then
            coproc get_username "$ROFI_INFO"
        elif [[ $1 == "password" ]]; then
            coproc get_password "$ROFI_INFO"
        else
            exit 1
        fi
    fi
else
    exit 1
fi
